name: ubuntu

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build
        run: cd && cargo install cross && git clone https://github.com/geph-official/geph4-client.git && cd geph4-client && cross build --release --locked  --target x86_64-unknown-linux-musl
        
      - uses: actions/upload-artifact@v3
        with:
          name: bin
          path: ~/geph4-client/target/x86_64-unknown-linux-musl/release/geph4-client
